import Head from 'next/head'
import { Container } from '@chakra-ui/react'

export default function Home() {
  return (
    <>
      <Head>
        <title>kimny</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="container.xl" padding={0}>
        kimny
      </Container>
    </>
  )
}
